# Generated by Django 5.2.6 on 2025-09-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0005_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(related_name="orders", to="shopapp.product"),
        ),
    ]
