# Generated by Django 5.2.6 on 2025-09-12 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0006_order_products"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["name", "price"]},
        ),
    ]
