# Generated by Django 5.2.6 on 2025-09-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0007_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="receipt",
            field=models.FileField(null=True, upload_to="orders/receipts"),
        ),
    ]
