# Generated by Django 5.2.6 on 2025-09-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0006_article_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(related_name="articles", to="blogapp.tag"),
        ),
    ]
